# Generated by Django 6.0.6 on 2026-07-03 12:35
# Hand-edited: wrapped in SeparateDatabaseAndState so this only updates
# Django's migration state (reviews now owns these models) without
# touching the database — the reviews_* tables already exist, renamed
# from litrevu_* in litrevu/migrations/0002_rename_tables_to_reviews.py.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('litrevu', '0003_remove_ticket_user_alter_userfollows_unique_together_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Ticket',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=128)),
                        ('description', models.TextField(blank=True, max_length=2048)),
                        ('image', models.ImageField(blank=True, null=True, upload_to='tickets/')),
                        ('time_created', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='Review',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('rating', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                        ('headline', models.CharField(max_length=128)),
                        ('body', models.TextField(blank=True, max_length=8192)),
                        ('time_created', models.DateTimeField(auto_now_add=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                        ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.ticket')),
                    ],
                ),
                migrations.CreateModel(
                    name='UserFollows',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'unique_together': {('user', 'followed_user')},
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
