# Generated by Django 6.0.6 on 2026-07-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='reviews_review',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='reviews_ticket',
        ),
        migrations.AlterModelTable(
            name='userfollows',
            table='reviews_userfollows',
        ),
    ]
