# Generated by Django 6.0.6 on 2026-07-03 12:35
# Hand-edited: wrapped in SeparateDatabaseAndState so this only updates
# Django's migration state (litrevu no longer owns these models) without
# touching the database — the tables were already renamed to reviews_*
# in 0002 and now belong to the `reviews` app's migration state instead.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('litrevu', '0002_rename_tables_to_reviews'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='ticket',
                    name='user',
                ),
                migrations.AlterUniqueTogether(
                    name='userfollows',
                    unique_together=None,
                ),
                migrations.RemoveField(
                    model_name='userfollows',
                    name='followed_user',
                ),
                migrations.RemoveField(
                    model_name='userfollows',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Review',
                ),
                migrations.DeleteModel(
                    name='Ticket',
                ),
                migrations.DeleteModel(
                    name='UserFollows',
                ),
            ],
            database_operations=[],
        ),
    ]
